# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.2.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox
import graph as g


class UiWidget(object):

    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(1640, 721)
        self.layoutWidget = QtWidgets.QWidget(Widget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 317, 701))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Kruskal = QtWidgets.QRadioButton(self.groupBox)
        self.Kruskal.setObjectName("Kruskal")
        self.verticalLayout.addWidget(self.Kruskal)
        self.Prim = QtWidgets.QRadioButton(self.groupBox)
        self.Prim.setObjectName("Prim")
        self.verticalLayout.addWidget(self.Prim)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(4, 20, 315, 321))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.StartNode = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartNode.sizePolicy().hasHeightForWidth())
        self.StartNode.setSizePolicy(sizePolicy)
        self.StartNode.setObjectName("StartNode")
        self.horizontalLayout.addWidget(self.StartNode)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.EndNode = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EndNode.sizePolicy().hasHeightForWidth())
        self.EndNode.setSizePolicy(sizePolicy)
        self.EndNode.setObjectName("EndNode")
        self.horizontalLayout_2.addWidget(self.EndNode)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.RibWeight = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RibWeight.sizePolicy().hasHeightForWidth())
        self.RibWeight.setSizePolicy(sizePolicy)
        self.RibWeight.setObjectName("RibWeight")
        self.horizontalLayout_3.addWidget(self.RibWeight)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.add_rib = QtWidgets.QPushButton(self.layoutWidget1)
        self.add_rib.setObjectName("add_rib")
        self.horizontalLayout_5.addWidget(self.add_rib)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.edgesOut = QtWidgets.QTextEdit(Widget)
        self.edgesOut.setGeometry(QtCore.QRect(330, 30, 181, 681))
        self.edgesOut.setObjectName("edgesOut")
        self.label = QtWidgets.QLabel(Widget)
        self.label.setGeometry(QtCore.QRect(340, 10, 111, 16))
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(Widget)
        self.label_5.setGeometry(QtCore.QRect(530, 10, 55, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Widget)
        self.label_6.setGeometry(QtCore.QRect(1080, 10, 55, 16))
        self.label_6.setObjectName("label_6")
        self.widget = QtWidgets.QWidget(Widget)
        self.widget.setGeometry(QtCore.QRect(520, 30, 1111, 681))
        self.widget.setObjectName("widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.graphView = QtWidgets.QGraphicsView(self.widget)
        self.graphView.setObjectName("graphView")
        self.horizontalLayout_6.addWidget(self.graphView)
        self.treeView = QtWidgets.QGraphicsView(self.widget)
        self.treeView.setObjectName("treeView")
        self.horizontalLayout_6.addWidget(self.treeView)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)
        self.graph = g.Graph()
        self.tree = None
        self.graphScene = QtWidgets.QGraphicsScene()
        self.treeScene = QtWidgets.QGraphicsScene()
        self.validator = QtGui.QIntValidator(0, 10000)
        self.RibWeight.setValidator(self.validator)
        self.add_rib.clicked.connect(self.add_edge)
        self.pushButton.clicked.connect(self.create_tree)
        self.alert = QMessageBox()
        self.alert.setIcon(QMessageBox.Icon.Critical)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.groupBox.setTitle(_translate("Widget", "Algorithm"))
        self.Kruskal.setText(_translate("Widget", "Kruskal"))
        self.Prim.setText(_translate("Widget", "Prim"))
        self.pushButton.setText(_translate("Widget", "Create net tree"))
        self.groupBox_2.setTitle(_translate("Widget", "New rib"))
        self.label_3.setText(_translate("Widget", "Start node:"))
        self.label_4.setText(_translate("Widget", "End node:"))
        self.label_2.setText(_translate("Widget", "Rib weight:"))
        self.add_rib.setText(_translate("Widget", "Add rib"))
        self.label.setText(_translate("Widget", "Graph edges"))
        self.label_5.setText(_translate("Widget", "Graph"))
        self.label_6.setText(_translate("Widget", "MST"))

    def add_edge(self):
        try:
            if len(self.StartNode.text()) == 0 or len(self.EndNode.text()) == 0 or len(self.RibWeight.text()) == 0:
                self.alert.setText("You must fill all node information!")
                self.alert.exec()
                return
            self.graph.add_edge(str(self.StartNode.text()), str(self.EndNode.text()), int(self.RibWeight.text()))
            self.graph.show_graph()
            pix = QtGui.QPixmap("graph.png")
            item = QtWidgets.QGraphicsPixmapItem(pix)
            self.graphScene.addItem(item)
            self.graphView.setScene(self.graphScene)
            self.edgesOut.setPlainText(self.graph.string_ribs())
        except NameError as e:
            self.alert.setText(str(e))
            self.alert.exec()
            return

    def create_tree(self):
        if self.Kruskal.isChecked():
            try:
                self.tree = g.KruskalAlgorithm(self.graph)
                self.tree.show_tree()
                pix = QtGui.QPixmap("net_tree.png")
                item = QtWidgets.QGraphicsPixmapItem(pix)
                self.treeScene.addItem(item)
                self.treeView.setScene(self.treeScene)
                return
            except IndexError as e:
                self.alert.setText(str(e))
                self.alert.exec()
                return
        if self.Prim.isChecked():
            try:
                self.tree = g.PrimAlgorithm(self.graph)
                self.tree.show_tree()
                pix = QtGui.QPixmap("net_tree.png")
                item = QtWidgets.QGraphicsPixmapItem(pix)
                self.treeScene.addItem(item)
                self.treeView.setScene(self.treeScene)
                return
            except IndexError as e:
                self.alert.setText(str(e))
                self.alert.exec()
                return
        else:
            self.alert.setText("You must choose algorithm first!")
            self.alert.exec()
            return


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Window = QtWidgets.QMainWindow()
    ui = UiWidget()
    ui.setupUi(Window)
    Window.show()
    sys.exit(app.exec())
